### ISSUE TITLE
image comparison with certain misMatch % difference is not allowed to certify via assertion

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/visual-testing#286]
WebdriverIO Version:
8.35.1

Node.js Version
18

Wdio Visual service version
4.1.0

Issue: I have certified one test case of image comparison like this:
await expect(element).toMatchElementSnapshot("tagName")

However there's a difference of certain % with baseline image. So I have updated my assertion like this:
await expect(element).toMatchElementSnapshot("tagName", 2) <--- in order to pass this test case with misMatchPercenatage diff of 2 or less than 2% but while running it gave error in terminal

Error: Expected image to have a mismatch percentage of 2%, but was 1.8536803906635%

I do know another way to achieve the same thing but it requires 2 steps:
const misMatchPercentage: number = await browser.checkElement(element, "tagName");
await expect(misMatchPercentage).toBeLessThanOrEqual(2);

Can we achieve the same thing with one line of assertion ?

cc: @jt-brevitaz

**Comment by wswebcreation** [comment]
Found the issue, this will be solved with https://github.com/webdriverio/visual-testing/pull/287

**Comment by jt-brevitaz** [comment]
Hi @wswebcreation the bug seems to be fixed but I found one small issue in it. When I pass misMatch number 5 as 2nd parameter in **await expect(element).toMatchElementSnapshot("label", 5);** like this it gives me error

`Expected image to have a mismatch percentage of 2%, but was 0%
Please compare the images manually and update the baseline if the new screenshot is correct.

Baseline: <baseline_path_to_that_screenshot>
Actual Screenshot: <actual_path_to_that_screenshot>
Difference: undefined`

Can you please confirm from your end is it an issue or not. 0 < 2 lol still it throws error.

**Comment by wswebcreation** [comment]
@jt-brevitaz 
Hmm, I'm testing it here and I don't have an issue, are you sure you're on the latest version, secondly can you create a reproducible example?
